### ISSUE TITLE
Question relative to initial Camera node position

### ISSUE THREAD

**Issue by tensorfreitas** [hannabjorgvins/augmented-reality#1]
Hi, 

I was trying to recreate a similar AR application to yours, when I found this repository.

The question is why do you put the initial position of the camera node to (0,0,15) and not (0,0,0)?

Thank you for your time.

**Comment by Robinseibold** [comment]
Hi!

It's been a while since we finished this project, as I recall the initial camera position should not affect the result, since its later repositioned in the `setCameraTransformationMatrixTo` method in [ModelView](https://github.com/hannabjorgvins/augmented-reality/blob/master/AugmentedReality/AugmentedReality/ModelView.swift#l55)

It might just be some leftover code from when we played around with scene kit in the beginning of the project. I also uploaded our [report](https://github.com/hannabjorgvins/augmented-reality/blob/master/paper.pdf) if you want to read about our solution for this AR application.

Cheers.

**Comment by tensorfreitas** [comment]
Thank you so much @Robinseibold I will read it and analyze what is missing in my app. Thank you so much for the effort!

**Comment by tensorfreitas** [comment]
Thank you so much, it really resolved the problem in my app. Thank you for your time, Best Regards.

**Comment by Robinseibold** [comment]
No problem, glad we could help! :)
